[package]
name = "ph-alfredworkflow"
version = "0.0.0"
edition = "2024"
rust-version = "1.89.0"
publish = false

[dependencies]
anycase = "0.1.0"
anyhow = "1.0.99"
constcat = "0.6.1"
home = "0.5.11"
itermore = { version = "0.8.0", features = ["std", "sorted"] }
jiff = "0.2.15"
log = { version = "0.4.28", features = ["std"] }
powerpack = { version = "0.7.0", features = ["cache", "logger"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sha1 = "0.10.6"
strsim = "0.11.1"
then = "0.1.0"
ureq = { version = "3.1.0", features = ["native-tls", "json"] }

[lints.rust]
unknown_lints = "allow"
elided_lifetimes_in_paths = "warn"
let_underscore_drop = "warn"
unsafe_op_in_unsafe_fn = "warn"

[lints.clippy]
if_not_else = "warn"
items_after_statements = "warn"
semicolon_if_nothing_returned = "warn"
use_self = "warn"
